---
stages:
  - test
  - build
  - release

.go_template_defaults:
  stage: test
.semver_template_defaults:
  stage: release
variables:
  SEMVER_PREFIX: v
include:
  - remote: https://gitlab.com/bonsai-oss/organization/ci-templates/-/raw/main/templates/language/go.yml
  - remote: https://gitlab.com/bonsai-oss/organization/ci-templates/-/raw/main/templates/release/semver.yml

.build-template:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug@sha256:2562c4fe551399514277ffff7dcca9a3b1628c4ea38cb017d7286dc6ea52f4cd
    entrypoint: [ "" ]
  rules:
    - if: $CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile-${CONTAINER_NAME}"
      --destination "${CI_REGISTRY_IMAGE}/${CONTAINER_NAME}:${CI_COMMIT_TAG}"
      --destination "${CI_REGISTRY_IMAGE}/${CONTAINER_NAME}:${CI_COMMIT_SHORT_SHA}"
      --destination "${CI_REGISTRY_IMAGE}/${CONTAINER_NAME}:latest"

build database:
  extends: .build-template
  variables:
    CONTAINER_NAME: database

build ingress:
  extends: .build-template
  variables:
    CONTAINER_NAME: ingress
